### ISSUE TITLE
Set minimum deployment target to 8.0

### ISSUE THREAD

**Issue by derpoliuk** [eggheadgames/ReceiptKit#12]
`carthage update` generates output:

```
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
```

We need set minimum target to iOS 8 to get rid of this message.

**Comment by mikemee** [comment]
Unfortunately, without this there is an error uploading an archive for app store submission:

![archive-failed](https://cloud.githubusercontent.com/assets/550990/18696935/b8a567fc-7f71-11e6-866b-e458380f5d52.jpg)
