### ISSUE TITLE
Remove release tags from develop branch

### ISSUE THREAD

**Issue by rudolf-adamkovic** [eggheadgames/ReceiptKit#16]
Also remove releases from GitHub.

**Comment by mikemee** [comment]
> Also remove releases from GitHub

Why?

**Comment by derpoliuk** [comment]
> Also remove releases from GitHub.

This breaks CI builds of apps that rely on ReceiptKit.

 I don't think that non-proper way of adding releases is good enough reason to delete existing releases from public repo.

**Comment by mikemee** [comment]
Executive decision. Leave it as it is. Thx.
