### ISSUE TITLE
Rename without "-kit" suffix

### ISSUE THREAD

**Issue by rudolf-adamkovic** [eggheadgames/ReceiptKit#23]

**Comment by mikemee** [comment]
Done

**Comment by salutis** [comment]
Wait

**Comment by rudolf-adamkovic** [comment]
@mikemee Just `Receipt` is misleading as the framework doesn't represent a receipt. If we want to drop the suffix, we need to come up with a meaningful name.

**Comment by mikemee** [comment]
ARGH!

**Comment by rudolf-adamkovic** [comment]
What about `apple-receipt-validator`?

**Comment by mikemee** [comment]
`apple-receipt-tools`
`apple-receipt-utils`
`apple-receipt-utilities`
`apple-receipt-helpers`
`apple-receipt-misc`

**Comment by mikemee** [comment]
validator makes me think of all those server-side validators. It doesn't really do any of that.

**Comment by mikemee** [comment]
@salutis

**Comment by rudolf-adamkovic** [comment]
@mikemee Actually, it does server-side validation.

The official document is called [Validating Receipts With the App Store](https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html).

**Comment by mikemee** [comment]
@salutis But this library doesn't do validation (does it??).

Maybe we should get #20 done before we rename again. By documenting it, we'll have a clearer idea of what this code is for.

**Comment by rudolf-adamkovic** [comment]
@mikemee 

Other related documents are [About Receipt Validation](https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Introduction.html) and [Validating Receipts Locally](https://developer.apple.com/library/content/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateLocally.html).

**Comment by rudolf-adamkovic** [comment]
@mikemee  

> But this library doesn't do validation (does it??).

It does. It's the whole point of this framework. 😄

**Comment by mikemee** [comment]
@salutis 

> It's the whole point of this framework

Umm, that wasn't my understanding. There are a zillion frameworks that do receipt validation and we didn't need to create one for that. The point of this framework was to extract the purchase date of the original app so we could appropriately unlock volume 1 for earlier purchasers. A problem that no other receipt validation library appeared to handle.

Let's get #20 done first...

**Comment by rudolf-adamkovic** [comment]
@mikemee Yeah. Sorry for not being clear. It refreshes, fetches and validates the receipt. Once done, we can safely access the purchase date that's inside of the receipt.

**Comment by rudolf-adamkovic** [comment]
Looking at #20, `apple-receipt` is not a bad name. 😳

**Comment by rudolf-adamkovic** [comment]
Continues in #26.
